"""add_event_invite_code

Revision ID: ff168deb9a00
Revises: 4683d539f4ad
Create Date: 2025-11-22 23:47:02.063367

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'ff168deb9a00'
down_revision: Union[str, None] = '4683d539f4ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('CREATE EXTENSION IF NOT EXISTS vector')
    op.add_column('events', sa.Column('invite_code', sa.String(length=20), nullable=False))
    op.create_index(op.f('ix_events_invite_code'), 'events', ['invite_code'], unique=True)
    op.drop_index('memories_embedding_idx', table_name='memories', postgresql_with={'m': '16', 'ef_construction': '64'}, postgresql_using='hnsw')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('memories_embedding_idx', 'memories', ['embedding'], unique=False, postgresql_with={'m': '16', 'ef_construction': '64'}, postgresql_using='hnsw')
    op.drop_index(op.f('ix_events_invite_code'), table_name='events')
    op.drop_column('events', 'invite_code')
    # ### end Alembic commands ###
